_wandb:
    value:
        cli_version: 0.23.0
        e:
            lm49mcvbakyzb2ckffymkltnbmayvc72:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "213208080384"
                email: chwon02@naver.com
                executable: /usr/local/bin/python3
                git:
                    commit: ca6f3a5302c00acb424adbd2aaba2ec03b23533a
                    remote: https://github.com/chae-jpg/boaz_miniproj2_ctr.git
                host: Chaeui-MacBookAir.local
                memory:
                    total: "17179869184"
                os: macOS-26.2-arm64-arm-64bit-Mach-O
                program: /Users/cakenpeace/2025_EWHA/BOAZ/mp2/mp2/train.py
                python: CPython 3.14.0
                root: /Users/cakenpeace/2025_EWHA/BOAZ/mp2/mp2
                startedAt: "2025-11-26T05:38:04.112473Z"
                writerId: lm49mcvbakyzb2ckffymkltnbmayvc72
        m: []
        python_version: 3.14.0
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.14.0
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
att_dropout:
    value: 0
att_head_num:
    value: 2
att_layer_num:
    value: 3
att_res:
    value: true
autoint_dnn_hidden_units:
    value:
        - 32
        - 32
batch_size:
    value: 100
data_dir:
    value: ./data
data_loader:
    value: v1
data_name:
    value: final_preprocessed_df.parquet
deepfm_dropout:
    value:
        - 0.5
        - 0.5
deepfm_hidden_dims:
    value:
        - 32
        - 32
dnn_dropout:
    value: 0
dnn_use_bn:
    value: false
embedding_dropout:
    value: 0
embedding_size:
    value: 16
entity:
    value: BOAZminiprj2
epochs:
    value: 100
init_std:
    value: 0.0001
l2_reg_dnn:
    value: 0
l2_reg_embedding:
    value: 1e-05
lr:
    value: 0.001
model_type:
    value: autoint
num_workers:
    value: 4
project:
    value: ctr-models
run_name:
    value: autoint_baseline
save_dir:
    value: ./ckpts
seed:
    value: 42
use_cuda:
    value: cuda
weight_decay:
    value: 1e-05
